############# English navigation ##############

# main menu
[[main]]
name = "Inicio"
url = ""
weight = 1

[[main]]
name = "Acerca de"
url = "about/"
weight = 2

[[main]]
name = "Contacto"
url = "contacto/"
weight = 3

[[main]]
name = "Páginas"
url = "#"
weight = 3
hasChildren = true

  [[main]]
  parent = "Páginas"
  name = "Etiquetas"
  url = "tags/"
  weight = 1

  [[main]]
  parent = "Páginas"
  name = "Categorías"
  url = "categories/"
  weight = 2

# footer menu
[[footer]]
name = "Inicio"
url = "/"
weight = 1

[[footer]]
name = "Acerca de"
url = "about/"
weight = 2

[[footer]]
name = "Contacto"
url = "contacto/"
weight = 3

[[footer]]
name = "Política de privacidad"
url = "privacy-policy/"
weight = 4
