############# English navigation ##############

# main menu
[[main]]
name = "Inicio"
url = ""
weight = 1

[[main]]
name = "Conocenos"
url = "quienes-somos/"
weight = 2

[[main]]
name = "Contacto"
url = "contacto/"
weight = 3

[[main]]
name = "Categorias"
url = "categories/"
weight = 4

[[main]]
name = "Temas"
url = "tags/"
weight = 5

# footer menu
[[footer]]
name = "Inicio"
url = "/"
weight = 1

[[footer]]
name = "Conocenos"
url = "quienes-somos/"
weight = 2

[[footer]]
name = "Contacto"
url = "contacto/"
weight = 3

[[footer]]
name = "Política de privacidad"
url = "politica-de-privacidad/"
weight = 4
