############# Menú principal en español ##############

# menú principal
[[main]]
name = "Inicio"
url = ""
weight = 1

[[main]]
name = "Quienes somos"
url = "quienes-somos/"
weight = 2

[[main]]
name = "Contacto"
url = "contacta-con-nosotros/"
weight = 3

[[main]]
name = "Páginas"
url = "#"
weight = 4
hasChildren = true

  [[main]]
  parent = "Páginas"
  name = "Etiquetas"
  url = "tags/"
  weight = 1

  [[main]]
  parent = "Páginas"
  name = "Categorías"
  url = "categories/"
  weight = 2

# menú del pie de página
[[footer]]
name = "Inicio"
url = "/"
weight = 1

[[footer]]
name = "Contacto"
url = "contacta-con-nosotros/"
weight = 2

[[footer]]
name = "Contacto"
url = "contacta-con-nosotros/"
weight = 3

[[footer]]
name = "Política de privacidad"
url = "politica-de-privacidad/"
weight = 4
